optimizer:
  learning_rate:
    - [200000.0, 1.0e-3]
    - [300000.0, 5.0e-4]
    - [400000.0, 1.0e-4]
  params:
    wd:
      2.0e-4
    momentum:
      0.9
  lr_mult:
    0.02
  type:
    sgd

network:
  class:
    HybridNetCoarse
  scale:
    20.0