validation_steps:
  250

checkpoint_steps:
  1000

dataset:
  sintel

subsets:
  - training1
  - training2

optimizer:
  learning_rate:
    - [300000, 1.0e-4]
    - [400000, 5.0e-5]
    - [500000, 2.5e-5]
    - [600000, 1.25e-5]
    - [604000, 0.5e-5]