optimizer:
  learning_rate:
    - [300000, 1.0e-4]
    - [400000, 5.0e-5]
    - [500000, 2.5e-5]
    - [600000, 1.25e-5]

network:
  implementation:
    dilation

  conv6:
    dilation:
      2
  
  conv5:
    dilation:
      yes

