optimizer:
  learning_rate:
    - [100000.0, 5.0e-4]
    - [300000.0, 1.0e-4]
    - [400000.0, 5.0e-5]
  params:
    wd:
      0.0
  lr_mult:
    1.0
  type:
    adam

network:
  class:
    Spynet
  scale:
    32.0
  activation:
    typename:
      nn.LeakyReLU
    args:
      - 0.1
    